
export const UserActions = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILED:'LOGOUT_FAILED',
    LOGIN_ERROR:'LOGIN_ERROR',

    SIGN_UP_REQUEST:'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
    SIGN_UP_FAILED:'SIGN_UP_FAILED',
    SIGN_UP_ERROR:'SIGN_UP_ERROR',

}
